### ISSUE TITLE
ImportError: cannot import name 'qqplot' from 'seaborn_qqplot' (C:\Python37\lib\site-packages\seaborn_qqplot\__init__.py)

### ISSUE THREAD

**Issue by vinuthna91** [RonsenbergVI/seaborn-qqplot#15]
Hi, I tried installing seaborn-qqplot using below command 
python3 -m pip install seaborn-qqplot. 

Installation was successful. 
When I try "import seaborn_qqplot" on python3 terminal, there is no error. However, when I try "from seaborn_qqplot import qqplot", it throws me import error. Kindly help resolve this!

**Comment by RonsenbergVI** [comment]
Hello,

My apologies, the documentation is not up to date yet. I'll fix that today. In the meantime have a look at the example notebook:

https://github.com/RonsenbergVI/seaborn-qqplot/blob/master/examples/example.ipynb

It explains the new API. I have consolidated all methods in the same method:

```python
from seaborn_qqplot import pplot
```

the pplot kw argument 'kind' will help you select the type of probability plot you want to show: 

- 'q' : quantile plot (i.e. empirical values against empirical quantile function) - univariate
- 'p' : probability plot (i.e. empirical values against cumulative distribution function) - univariate
- 'qq': quantile function against quantile function - bivariate
- 'pp': cumulative distribution function against cumulative distribution function - bivariate

I am also working on a blog post on the topic. I'll add all of these in there when done (hopefully by the end of the week)

If you have any other question do not hesitate, happy to help.

Rene-Jean.

**Comment by vinuthna91** [comment]
Thanks for the quick reply.
I want to compare against the normal quantiles. Hence, can I use kind="qq" ?

**Comment by RonsenbergVI** [comment]
Yes do kind='qq'. If you want to compare against a specific distribution you need a scipy.stats.rv_continuous object. The basic code should be:

```python
from seaborn_qqplot import pplot
from scipy.stats import norm


pplot(dataframe, x="your_column", kind='qq', y=norm)

```

**Comment by vinuthna91** [comment]
Great, Thanks a lot for the quick help!

**Comment by vinuthna91** [comment]
Can you give other options that can be passed to pplot?

**Comment by RonsenbergVI** [comment]
I updated the recommendation, it took a bit longer that expected. I hope it still helps.
