### ISSUE TITLE
t missing in util.py - error when plotting confidence intervals

### ISSUE THREAD

**Issue by lenlan** [RonsenbergVI/seaborn-qqplot#4]
Currently 't' doesn't seem to refer to anything in util.py line 86: q_t = t.ppf(p, df)
and throws an error when trying to plot confidence intervals.

is this supposed to be the student t distribution?
In that case "from scipy.stats import t" is missing at top of document.

**Comment by RonsenbergVI** [comment]
issue fixed. thanks for flagging. If you're interested in contribution let me know!
